name: Naxi
version: 1.0.0
description: Does map stuff, but really just geocodes addresses with the Mapbox API right now.
url: lionsmouth.digital
developer: LionsMouth Digital
developer_url: lionsmouth.digital
